# Templates package 

from .prompts import (
    DEFAULT_TOOL_PROMPT,
    DEFAULT_CRITIC_SYSTEM_PROMPT,
    DEFAULT_CRITIQUE_PROMPT,
    DEFAULT_CORRECTION_PROMPT,
)

__all__ = [
    "DEFAULT_TOOL_PROMPT",
    "DEFAULT_CRITIC_SYSTEM_PROMPT",
    "DEFAULT_CRITIQUE_PROMPT",
    "DEFAULT_CORRECTION_PROMPT",
] 